version: '3.9'

services:
  mysql:
    image: mysql:latest
    container_name: db_farmacia
    environment:
      MYSQL_ROOT_PASSWORD: 256231
      MYSQL_DATABASE: dbfarmacia
    volumes:
      - volume-db-farmacia:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - redeapi

  farmacia_api:
    image: erivan41/app-farma:1.0
    container_name: farmacia_api
    ports:
      - "8081:8080"
    environment:
      MYSQL_HOST: db_farmacia
      MYSQL_DATABASE: dbfarmacia
    networks:
      - redeapi
    depends_on:
      - mysql 

networks:
  redeapi:
    driver: bridge

volumes:
  volume-db-farmacia:
